// apps/web/src/env.d.ts
//
// Ambient type references for the Astro runtime. The Clerk package ships
// its own `App.Locals` augmentation (carrying `auth`, `currentUser`,
// `authStatus`, etc.) — re-export that triple-slash reference here so
// `Astro.locals.auth(...)` is strongly typed across the app.
//
// `astro:middleware` is a virtual module surfaced by Astro's Vite plugin
// at runtime; its types are normally generated by `astro sync` into
// `.astro/types.d.ts`. We don't run `astro sync` in CI's typecheck step
// (it requires a working Astro build pipeline that, today, exits before
// emitting any output — see `package.json` → `build: "exit 0"`). The
// ambient declaration below mirrors Astro's published surface (`astro/
// dist/virtual-modules/middleware.d.ts`) so `apps/web/src/middleware.ts`
// can `import { defineMiddleware, sequence } from 'astro:middleware'`
// without TS2307. Landed by Story #562 / Task #573.
//
// Story #328 (Task #331) — Clerk SDK wiring for the web runtime.
// Story #562 (Task #573) — onboarding-gate middleware.

/// <reference types="astro/client" />
/// <reference types="@clerk/astro/env" />

declare module 'astro:middleware' {
  // The published Astro surface re-exports these two helpers from
  // `astro/dist/core/middleware/`. Re-declaring the shape here keeps
  // apps/web independent of Astro's internal export map.
  type MiddlewareNext = () => Promise<Response>;
  type MiddlewareHandler<C = unknown> = (
    context: C,
    next: MiddlewareNext,
  ) => Promise<Response> | Response | Promise<void> | void;

  export function defineMiddleware<C = unknown>(
    handler: MiddlewareHandler<C>,
  ): MiddlewareHandler<C>;

  export function sequence<C = unknown>(
    ...handlers: ReadonlyArray<MiddlewareHandler<C>>
  ): MiddlewareHandler<C>;
}
