// scripts/__tests__/baseline-stubs.test.mjs
//
// Pins the existing baselines/crap.json and baselines/maintainability.json
// to the envelope contract. Both files are generated by the Mandrel
// framework engine (update-crap-baseline.js / update-maintainability-baseline.js)
// and validated against the per-kind schemas hosted at .agents/schemas/baselines/.
//
// Invariants enforced here:
//   1. Both files validate against the envelope and their per-kind schema
//      under AJV.
//   2. Both baselines are primed (rows[] non-empty; rollup '*' carries real
//      measurements) per Story #375 and Story #1000.

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { describe, expect, it } from 'vitest';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SCHEMA_DIR = path.join(REPO_ROOT, '.agents', 'schemas', 'baselines');
const BASELINES_DIR = path.join(REPO_ROOT, 'baselines');

/**
 * Resolve the installed typhonjs-escomplex version by walking up from
 * REPO_ROOT — mirrors what .agents/scripts/lib/baselines/kinds/crap.js does
 * at runtime so this test stays in sync with the framework's kernel version.
 */
function resolveEscomplexVersion() {
  let dir = REPO_ROOT;
  while (true) {
    const pkgPath = path.join(dir, 'node_modules', 'typhonjs-escomplex', 'package.json');
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
      if (pkg && typeof pkg.version === 'string') return pkg.version;
    } catch {
      /* traverse up */
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

const ESCOMPLEX_KERNEL_VERSION = resolveEscomplexVersion();

function loadJson(file) {
  return JSON.parse(readFileSync(file, 'utf8'));
}

function buildAjv() {
  const ajv = new Ajv({ strict: false });
  addFormats(ajv);
  ajv.addSchema(
    loadJson(path.join(SCHEMA_DIR, 'baseline-envelope.schema.json')),
    'baseline-envelope.schema.json',
  );
  return ajv;
}

const STUBS = [
  {
    kind: 'crap',
    file: 'crap.json',
    schemaFile: 'crap.schema.json',
    rollupAxes: ['p50', 'p95', 'max', 'methodsAbove20'],
  },
  {
    kind: 'maintainability',
    file: 'maintainability.json',
    schemaFile: 'maintainability.schema.json',
    rollupAxes: ['min', 'p50', 'p95'],
  },
];

describe('baseline stubs (crap + maintainability)', () => {
  it.each(STUBS)('$kind stub carries an envelope-shaped document', ({ file }) => {
    const doc = loadJson(path.join(BASELINES_DIR, file));
    expect(doc).toHaveProperty('$schema');
    expect(doc).toHaveProperty('kernelVersion');
    expect(doc).toHaveProperty('generatedAt');
    expect(doc).toHaveProperty('rollup');
    expect(doc).toHaveProperty('rows');
  });

  it.each(STUBS)('$kind kernelVersion matches installed typhonjs-escomplex', ({ file }) => {
    const doc = loadJson(path.join(BASELINES_DIR, file));
    expect(doc.kernelVersion).toBe(ESCOMPLEX_KERNEL_VERSION);
  });

  it.each(STUBS)("$kind stub rollup carries the required '*' key", ({ file }) => {
    const doc = loadJson(path.join(BASELINES_DIR, file));
    expect(doc.rollup).toHaveProperty('*');
    expect(typeof doc.rollup['*']).toBe('object');
  });

  it.each(STUBS)('$kind stub rollup * declares every required axis', ({ file, rollupAxes }) => {
    const doc = loadJson(path.join(BASELINES_DIR, file));
    for (const axis of rollupAxes) {
      expect(doc.rollup['*']).toHaveProperty(axis);
    }
  });

  it.each(STUBS)('$kind baseline carries rows[] (primed in Story #375)', ({ file }) => {
    const doc = loadJson(path.join(BASELINES_DIR, file));
    expect(Array.isArray(doc.rows)).toBe(true);
    // Story #375 primed crap and maintainability against real
    // measurements. The previous "ships unprimed (rows[] empty)" pin
    // captured the pre-priming contract; from #375 forward both
    // baselines MUST carry rows so the corresponding `*:check` gates
    // can actually compare against something.
    expect(doc.rows.length).toBeGreaterThan(0);
  });

  it.each(STUBS)(
    '$kind rollup * carries real measurements (primed in Story #375)',
    ({ file, rollupAxes }) => {
      const doc = loadJson(path.join(BASELINES_DIR, file));
      // Replaces the previous "values are zero placeholders" pin. After
      // priming, at least one axis MUST be non-zero — otherwise the
      // `*:check` gate either misread the producer or the producer
      // emitted no data, both of which we want to fail loud.
      const someAxisNonZero = rollupAxes.some((axis) => {
        const v = doc.rollup['*'][axis];
        return typeof v === 'number' && v !== 0;
      });
      expect(someAxisNonZero).toBe(true);
    },
  );

  it.each(STUBS)(
    '$kind stub validates under AJV against its per-kind schema',
    ({ file, schemaFile }) => {
      const ajv = buildAjv();
      const schema = loadJson(path.join(SCHEMA_DIR, schemaFile));
      const validate = ajv.compile(schema);
      const doc = loadJson(path.join(BASELINES_DIR, file));
      const ok = validate(doc);
      if (!ok) {
        console.error(`AJV errors for ${file}:`, validate.errors);
      }
      expect(ok).toBe(true);
    },
  );

  it.each(STUBS)(
    "$kind stub's $schema pointer targets the matching per-kind schema",
    ({ file, schemaFile }) => {
      const doc = loadJson(path.join(BASELINES_DIR, file));
      expect(doc.$schema).toBe(`.agents/schemas/baselines/${schemaFile}`);
    },
  );
});
